services:
  google_chat_ai_layer_front:
    build:
      context: .
    container_name: google_chat_ai_layer_front
    volumes:
      - './app:/app'
    working_dir: /app
    ports:
      - '3000:3000'
